import type { Metadata } from "next";

import "./../sass/main.scss";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader
          color={Date.now() % 2 === 0 ? "#CE822F" : "#14a998"}
          showSpinner={false}
          height={4}
        />

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
